use_frameworks!

platform :ios, '10.0'

target 'MeherySender_Example' do
  pod 'MeherySender', :path => '../'

  target 'MeherySender_Tests' do
    inherit! :search_paths
  end
  
  target 'NotificationServiceExtension' do
    use_frameworks!
    pod 'MeherySender', :path => '../'
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
       end
    end
  end
end


